import logging

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List
from app.llm.personality import PersonalityEngine
from app.services.feedback import FeedbackService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/chat", tags=["chat"])
personality_engine = PersonalityEngine()


class ChatRequest(BaseModel):
    message: str
    context: Optional[str] = None


class ChatResponse(BaseModel):
    response: str
    mood: str
    tone: str
    citations: List[str] = []


@router.post("/")
async def chat(request: ChatRequest):
    try:
        response = personality_engine.generate_response(
            query=request.message,
            context=request.context
        )
        feedback_service = FeedbackService()
        learning_result = feedback_service.learn_from_conversation(
            request.message,
            response
        )
        if learning_result["learned"]:
            logger.info("Learned from conversation: %s", learning_result)
        emotional_state = personality_engine.get_emotional_state()
        return ChatResponse(
            response=response,
            mood=emotional_state.get("mood", "neutral"),
            tone=emotional_state.get("tone", "warm"),
            citations=["Generated by AI with personality"]
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/emotional-state")
async def get_emotional_state():
    """Get the current emotional state of the conversation."""
    return personality_engine.get_emotional_state()


@router.post("/reset")
async def reset_conversation():
    """Reset the conversation history."""
    personality_engine.reset_conversation()
    return {"status": "reset", "message": "Conversation reset"}
